### ISSUE TITLE
Iterators

### ISSUE THREAD

**Issue by breese** [pdimov/hash2#1]
The `update()` function of the various hash functions currently takes a pointer-size pair. Can this be changed to, or extended with, an iterator pair?

The reason i am asking is that I would like to transform the input before I calculate its hash value, and I would like to avoid having to store a copy of the transformed input. This can be done by using a transforming iterator.

**Comment by pdimov** [comment]
The HashAlgorithm concept is low-level and one design goal is to make writing hash algorithms easy by not burdening them with complexity.

The way to pass an iterator range to a hash algorithm `h` is `hash_append_range( h, first, last );`.

**Comment by breese** [comment]
`hash_append_range` will work for my purposes (or better yet repeated calls to `hash_append` so I do not have to create a transforming iterator in the first place.)
